### ISSUE TITLE
Створити сторінку для відображення та створення курсів

### ISSUE THREAD

**Issue by yevgeniusr** [YevheniiRa/mentorship_guild#5]
https://flask.palletsprojects.com/en/1.1.x/tutorial/views/

Коли GET повертається сторінка з списком всіх курсів
Коли POST то створюється новий курс і редірект на список курсів

**Comment by lame-over** [comment]
flask
@bp.route('/create_course', methods=('GET', 'POST'))
def course():
    if request.method == 'POST':
        course_name = request.form['name']
        descr = request.form['descr']
        db = get_db()
        error = None

        if not name:
            error = 'Name is required.'
        elif not descr:
            error = 'Please enter description'
        elif db.execute(
            'SELECT * FROM course WHERE name = ?', (name,)
        ).fetchone() is not None:
            error = 'Name of course {} is already registered.'.format(name)

        if error is None:
            db.execute(
                'INSERT INTO user (name, password) VALUES (?, ?)',
                (name, descr)
            )
            db.commit()
            return redirect(url_for('auth.create_course'))

        flash(error)

    return render_template('create_course.html')
@bp.route('/course_list', methods=('GET', 'POST'))
def list():
	return render_template(url_for('auth.course_list'))








create_course.html

<!DOCTYPE HTML>
<html>
    <head>

        <meta charset="UTF-8">

        <title>create course</title>
      <link rel="stylesheet" href="../static/css/XD.css">
      <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet"> 
      <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"> 
</head>
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Register{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="name">Name of course</label>
    <input name="name" id="name" required>
    <label for="password">Description</label>
    <input type="descr" name="descr" id="descr" required>
    <input type="submit" value="Register">
  </form>
<div class="block"></div>
<script type="text/javascript" src="../static/js/script.js"></script>
{% endblock %}





course_list.html


<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Course list</title>
  <link rel="stylesheet" href="../static/css/XD.css">
  <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"> 
</head>
<body>
{% extends 'base.html' %}
{% for course in course %}
<test>{{course.name}}<br>{{course.descr}}</test>
{%endfor%}



<script type="text/javascript" src="../static/js/script.js"></script>
</body>
</html>

**Comment by Matsenko** [comment]
Completed
