### ISSUE TITLE
Сторити основну сторінку

### ISSUE THREAD

**Issue by yevgeniusr** [YevheniiRa/mentorship_guild#6]
https://flask.palletsprojects.com/en/1.1.x/tutorial/views/

Повинно повертати основну сторінку з кнопкою реєстрації та логінки

**Comment by SuperCreator2007** [comment]
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>Home</title>
 </head>
 <body> 
  <form>
   <p><input type = button value="РЕЄСТРАЦІЯ"></p>
  </form>
 </body>
</html>

**Comment by SuperCreator2007** [comment]
from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
@app.route("/home")
def index():
    return render_template("home.html")

**Comment by SuperCreator2007** [comment]
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>Home</title>
 </head>
 <body> 
  <form>
   <p><input type = button value="РЕЄСТРАЦІЯ"></p>
  </form>
 </body>
</html>

**Comment by SuperCreator2007** [comment]
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>Home</title>
 </head>
 <body> 
  <form>
   <h1><link "ПОСИЛАННЯ НА РЕЄСТРАЦІЮ">РЕЄСТРАЦІЯ або <link "ПОСИЛАННЯ НА ВХІД">ВХІД</h1>
  </form>
 </body>
</html>

**Comment by SuperCreator2007** [comment]
![image](https://user-images.githubusercontent.com/68220420/89714936-be624380-d9aa-11ea-8abd-ab4708dfcf67.png)

**Comment by SuperCreator2007** [comment]
![image](https://user-images.githubusercontent.com/68220420/89714952-da65e500-d9aa-11ea-805c-9268901cd8b7.png)

**Comment by SuperCreator2007** [comment]
![image](https://user-images.githubusercontent.com/68220420/90001671-64a79500-dc9a-11ea-8828-8c415e528933.png)

**Comment by SuperCreator2007** [comment]
![image](https://user-images.githubusercontent.com/68220420/90001731-77ba6500-dc9a-11ea-9395-3775962804eb.png)
